# Generated by Django 4.2.2 on 2023-06-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=100)),
                ('contrasena_confirmacion', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=False)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes_perfil/')),
            ],
        ),
    ]
