# Generated by Django 4.2.2 on 2023-06-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
